# Generated by Django 3.0.8 on 2020-07-23 10:36

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200723_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-prof-pic.jpg', upload_to=account.models.upload_location),
        ),
    ]
